### ISSUE TITLE
error, Can not connect to CivitAI.

### ISSUE THREAD

**Issue by dada5872** [a2569875/lora-prompt-tool#8]
![image](https://github.com/a2569875/lora-prompt-tool/assets/69775612/d6b31bb2-38d2-45bc-80f5-efca27d83981)

![image](https://github.com/a2569875/lora-prompt-tool/assets/69775612/d8cf1c9e-995b-42b2-b49d-2db1c9d2377a)

**Comment by DaisyHunter** [comment]
如果是lora无法连接网络的话，那是插件bug。如果是模型无法连接civitai的话，那存粹是你网络设置问题。

**Comment by gaz916** [comment]
如果是插件bug，那可以怎么修复呢，我的魔法可以正常上C站，但使用这个插件，一只显示error, Can not connect to CivitAI
显示这个错误：Error loading script: tools.py
    Traceback (most recent call last):
      File "H:\00-sd-webui-aki-v4\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\00-sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\00-sd-webui-aki-v4\extensions\PBRemTools\scripts\tools.py", line 11, in <module>
        from scripts.td_abg import get_foreground
      File "H:\00-sd-webui-aki-v4\extensions\PBRemTools\scripts\td_abg.py", line 37, in <module>
        model_path = huggingface_hub.hf_hub_download(
      File "H:\00-sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
        return fn(*args, **kwargs)
      File "H:\00-sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\file_download.py", line 1291, in hf_hub_download
        raise LocalEntryNotFoundError(
    huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.
